name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10, 12, 14]  # Different Node.js versions to test against
        os: [ubuntu-latest, windows-latest]  # Different OS environments

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matix.os }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies  ${{ matix.os }}
        run: echo npm install

      - name: Run tests  ${{ matix.os }}
        run: echo npm test
